export const GREETINGS = [
  "Welcome back today.",
  "Good to see you.",
  "Ready when you are.",
  "Everything looks in place.",
  "A steady day ahead.",
  "Good to have you back.",
  "Back on the checklist.",
  "Another quiet pass through.",
  "Here when you need it.",
  "The panel is set.",
  "Today starts clean here.",
  "A calm place to work.",
  "The details are ready.",
  "Your records are nearby.",
  "Good to have you here.",
  "A clear page today.",
  "The day is lined up.",
  "All set for review.",
  "Nothing extra, just ready.",
  "Your workflow is open.",
  "Back to the essentials.",
  "A smooth return today.",
  "Everything stays within reach.",
  "The next step is here.",
  "A good place to begin.",
  "Ready for the next logbook.",
  "The day looks orderly.",
  "Quiet progress starts here.",
  "Another page, same focus.",
  "The next task is ready.",
  "Your tools are in place.",
  "A steady screen today.",
  "The record stays current.",
  "The day is holding steady.",
  "A clear line forward.",
  "The next entry awaits.",
  "Good to resume here.",
  "Nothing rushed today.",
  "The essentials are ready.",
  "Back to what matters.",
  "One step at a time.",
  "The view stays clear.",
  "Back where things fit.",
  "A clean start again.",
  "The details are standing by.",
  "Ready for another pass.",
  "This page is prepared.",
  "Everything remains within view.",
  "Take it one step at a time.",
  "A good moment to review.",
  "The line is set.",
  "All looks orderly here.",
  "The workbench is open.",
  "Back to a steady rhythm.",
  "The next action is simple.",
  "Everything is set.",
  "The notes are close.",
  "Today feels well arranged.",
  "The path stays straightforward.",
  "Nothing out of place.",
  "A steady hand helps.",
  "The page stays ready.",
  "The day is ready.",
  "The sequence is intact.",
  "A calm return to work.",
  "Good to see you here.",
  "The next check is ready.",
  "All set for the next item.",
  "The queue is light today.",
  "A measured pace works well.",
  "The day remains on track.",
  "The details stay close.",
  "Ready for the next review.",
  "A grounded place to work.",
  "The panel stays clear.",
  "Everything is easy to find.",
  "A good page for focus.",
  "The next step is nearby.",
  "Back in familiar airspace.",
  "Nothing loud, just ready.",
  "The day can move forward.",
  "A clean handoff to today.",
  "The checklist is ready.",
  "Your setup is still here.",
  "A little progress goes far.",
  "The next pass looks clear.",
  "A quiet start helps.",
  "The record is ready again.",
  "Another steady page awaits.",
  "The flow remains simple.",
  "A good day for clarity.",
  "The runway looks open.",
  "Your notes are in order.",
  "The next review is close.",
  "A calm pace matters.",
  "Everything stays where expected.",
  "The page is ready again.",
  "A useful place to resume.",
  "The details remain steady.",
  "Ready for the next revision.",
  "A quiet cockpit of tasks.",
  "The work can stay simple.",
  "Good to return here.",
];

export function getDeterministicGreeting(userId: string) {
  const today = new Date().toDateString();
  const seed = userId + today;

  let hash = 0;
  for (let index = 0; index < seed.length; index += 1) {
    hash = (hash << 5) - hash + seed.charCodeAt(index);
    hash |= 0;
  }

  const greetingIndex = Math.abs(hash) % GREETINGS.length;
  return GREETINGS[greetingIndex];
}
