-- Local baseline marker for production migration 20260722195001_separate_platform_admin_organization_context.sql.
-- The schema-only baseline in 20260707193726_aircraft_visibility.sql already includes this migration.
-- Original SQL is preserved under supabase/archive/remote-migrations-fetched/.
