-- Local baseline marker for production migration 20260722124959_organizations_and_shared_fleet.sql.
-- The schema-only baseline in 20260707193726_aircraft_visibility.sql already includes this migration.
-- Original SQL is preserved under supabase/archive/remote-migrations-fetched/.
