-- Local baseline marker for production migration 20260722163029_index_notification_reads_by_user.sql.
-- The schema-only baseline in 20260707193726_aircraft_visibility.sql already includes this migration.
-- Original SQL is preserved under supabase/archive/remote-migrations-fetched/.
