-- Local baseline marker for production migration 20260723205542_retire_legacy_aircraft_rpcs_from_data_api.sql.
-- The schema-only baseline in 20260707193726_aircraft_visibility.sql already includes this migration.
-- Original SQL is preserved under supabase/archive/remote-migrations-fetched/.
