-- Local baseline marker for production migration 20260722131742_organization_teaching_roles_and_endorsement_records.sql.
-- The schema-only baseline in 20260707193726_aircraft_visibility.sql already includes this migration.
-- Original SQL is preserved under supabase/archive/remote-migrations-fetched/.
