-- Local baseline marker for production migration 20260707193817_aircraft_visibility_policy_cleanup.sql.
-- The schema-only baseline in 20260707193726_aircraft_visibility.sql already includes this migration.
-- Original SQL is preserved under supabase/archive/remote-migrations-fetched/.
