-- Local baseline marker for production migration 20260722161418_restrict_organization_notification_rpc.sql.
-- The schema-only baseline in 20260707193726_aircraft_visibility.sql already includes this migration.
-- Original SQL is preserved under supabase/archive/remote-migrations-fetched/.
